[global]

logging = file
log file = /tmp/samba.log

log level = 1
max log size = 0

vfs objects = full_audit

full_audit:prefix = %u|%S
full_audit:success = connect disconnect mkdir rmdir read write rename unlink
full_audit:failure = all

full_audit:facility = LOCAL7
full_audit:priority = NOTICE

#########################################

[ebooks]
path = /libraryit/ebooks

valid users = @readonly,@staff
write list = @staff

read only = yes
browseable = yes

force user = root
force group = staff

create mask = 0664
directory mask = 0775

#########################################

[papers]
path = /libraryit/papers

valid users = @readonly,@staff
write list = @staff

read only = yes
browseable = yes

force user = root
force group = staff

create mask = 0664
directory mask = 0775

#########################################

[sourcecode]
path = /libraryit/sourcecode

valid users = @staff
write list = contributor,librarian

read only = no
browseable = no

force user = root
force group = staff

create mask = 0660
directory mask = 0770

#########################################

[docs]
path = /libraryit/docs

valid users = @readonly,@staff
write list = librarian

read only = yes
browseable = yes

force user = root
force group = staff

create mask = 0664
directory mask = 0775
